import random
import datetime
from datetime import date
from flask import Flask, abort, render_template, redirect, url_for, flash, request, make_response
from flask_frozen import Freezer
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash
import smtplib
import os
import io

# APP ######################################
app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('APP_SECRET')


# Shows About Site #######################################
@app.route("/about/")
def about():
    return render_template("about.html")


# Home #######################################
@app.route("/")
def index():
    art_path = os.path.join(app.static_folder, "assets", "img", "art")
    projects = []
    
    # Artwork Info
    artworks =  {
        "strange_dogs": {
            "title": "Strange Dogs",
            "subtitle": "Acrylic on recycled Canvas, 95 x 135 cm",
            "year": 2020,
            "description": "The background is the result of edge detection in a photo of a tree cross-section. If you look closely, you can see an overpainted Udo Lindenberg."
        },
        "falco": {
            "title": "Falco",
            "subtitle": "Acrylic on Canvas, 140 x 120 cm",
            "year": 2019,
            "description": "Falco's portrait was drawn by hand. The story behind it is similar to that of Marilyn's portrait. It was overpainted countless times until it bore a certain resemblance to the original.<br>Because this process was too time-consuming, I started working on my vertical pen plotter project."
        },
        "polygone_1": {
            "title": "Polygone 1",
            "subtitle": "Acryl on Canvas, 100 x 120 cm",
            "year": 2020,
            "description": "This is my first image made with my vertical pen plotter.<br>The plotter uses a Raspberry Pi to run open source software <a href='https://github.com/bertlr/vplotter'>(github)</a> that controls two stepper motors and a servo motor. These motors draw polygons (generated by Python code) onto the canvas in two steps.<br>As you can see, the first attempts went beyond the image area, and the drawing in the lower left corner did not start where it should have.",
        },
         "girl_with_headphones": {
            "title": "Girl with Headphones",
            "subtitle": "Ink on paper, 60 x 84 cm",
            "year": 2024,
            "description": "I used AI to create the image template and DrawingBotV3 for edge detection and style inspiration.<br>However, in the end, I only drew the outlines with the vertical pen plotter, as completing the entire plot would have taken dozens of hours. I drew the rest by hand.",
        },
        "birds_nest": {
            "title": "Bird's Nest",
            "subtitle": "Acrylic on Canvas, 160 x 120 cm",
            "year": 2023,
            "description": "As AI is the dominant topic of our time, I used it to create some artwork. My workflow was straightforward. First, I analysed an AI-generated image using edge detection to convert the outlines of the pixel graphic into vectors. Next, I digitally retouched the image using a graphics tablet, as edge detection had not picked up all the desired parts of the image. Finally, I created a plotter sketch with a waterproof pen and painted the image with acrylics.",
        },
        "clint_stares_at_you": {
            "title": "Clint Stares at You",
            "subtitle": "Acryl on Canvas, 100 x 120 cm",
            "year": 2020,
            "description": "The portrait was drawn by hand on paper and then digitised. I used the open-source vector graphics editor Inkscape to convert the pixel-based images into vectors, enabling me to scale them without losing quality. These vector paths can then be converted into G-code. G-code is a programming language used to control automated machine tools such as CNC machines. This is the input format for the vertical plotter which consists of a Raspberry Pi controlled by open-source software available on GitHub. The Raspberry Pi reads the G-code and uses it to control the movement of two stepper motors and a servo motor. These draw the sketch onto the canvas.<br>The background was painted before the plotter started drawing. I used a waterproof pen for the plotter sketch and acrylic paint for the rest.",
        },
        "london_dna": {
            "title": "London DNA",
            "subtitle": "Acrylic on recycled Ikea Canvas, 95 x 135 cm",
            "year": 2023,
            "description": "For this picture, I used a recycled canvas made of plastic. This time, I documented both the original image and the individual processing steps.<br>The DNA sketch is based on images taken with an electron microscope.",
        },
        "birds_nest_black_version": {
            "title": "Bird's Nest Black Version",
            "subtitle": "Ink / Watercolor on Paper, 60 x 84 cm",
            "year": 2024,
            "description": "3rd Version of Bird's Nest.",
        },
        "birds_nest_line_art": {
            "title": "Bird's Nest Line Art",
            "subtitle": "Ink on Paper, 51 x 72 cm",
            "year": 2024,
            "description": "The image template was essentially the same as that for the Bird's Nest.<br>This time, I used DrawingBotV3, which converts images into stylised drawings that can be exported as vector graphics. Please note that I only plotted part of the image, as plotting the whole thing would have taken over 30 hours. I drew the rest by hand.",
        },
        "polygone_2": {
            "title": "Polygone 2",
            "subtitle": "Acryl on Canvas, 100 x 120 cm",
            "year": 2020,
            "description": "This is my second image of a vertical pen plotter.<br>The polygons were generated automatically by software and drawn onto the finished background in two steps.<br>The white pen obviously loses colour intensity because it has a pump mechanism. This is not recommended at all for a pen plotter, especially if you leave the room frequently and let the plotter do its work.",
        },
        "jellyfish": {
            "title": "Jellyfish",
            "subtitle": "Ink on Paper, 59 x 84 cm",
            "year": 2021,
            "description": "Automatically generated line art plotted by a vertical pen plotter.",
        },
        "just_another_marilyn": {
            "title": "Just Another Marilyn",
            "subtitle": "Acrylic on Canvas, 100 x 140 cm",
            "year": 2019,
            "description": "The picture of Marilyn was painted before the time of the plotter, so it took weeks to get it halfway right. Once it was on the wall, I discovered so many errors that I had to rework it.",
        },
        "flamingo_attack": {
            "title": "Flamingo Attack",
            "subtitle": "Ink on Paper, 60 x 84 cm",
            "year": 2023,
            "description": "Hitchcock's The Birds 2: Revenge of the Flamingos.",
        },
        "samurai_girl": {
            "title": "Samurai Girl",
            "subtitle": "Acryl on Canvas, 140 x 120 cm",
            "year": 2023,
            "description": "I used AI to generate the image of the girl, and DrawingBotV3 to detect the edges.",
        },
        "basset_hound": {
            "title": "Basset Hound",
            "subtitle": "Acrylic on Canvas, 100 x 135 cm",
            "year": 2024,
            "description": "Impassivity in folds.",
        },
        "three_apes": {
            "title": "Three Apes",
            "subtitle": "Ink on Paper, 60 x 84 cm",
            "year": 2024,
            "description": "Three apes waiting for the end of the world.",
        },
        "vietnamese_dog": {
            "title": "Vietnamese Dog",
            "subtitle": "Chalk Paint/Watercolor/Wax Crayon on Recycled Canvas, 95 x 135 cm",
            "year": 2024,
            "description": "Nothing more to say.",
        },
        "bloch's_cousin": {
            "title": "Bloch's Cousin",
            "subtitle": "Mixed Media on Recycled Canvas, 100 x 140 cm",
            "year": 2025,
            "description": "",
        },
        "london_showdown": {
            "title": "London Showdown",
            "subtitle": "Acrylic on recycled Ikea Canvas, 95 x 135 cm",
            "year": 2025,
            "description": "London DNA reworked.",
        }
    }


    for folder in sorted(os.listdir(art_path)):
        folder_path = os.path.join(art_path, folder)
        # print(f"Checking folder: {folder_path}")
        if os.path.isdir(folder_path):
            files = sorted(os.listdir(folder_path))
            # print(f"Processing folder: {folder}")
            files = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.webp','.mp4', '.mov', '.webm'))]
            
            if files:
                preview = f'assets/img/art/{folder}/{files[0]}'  # first image as preview
                # print(f"Preview files: {preview}")
            else:
                continue

            projects.append({
                "name": folder,
                "preview": preview, # first image or video as preview
                "files": files,
                "year": artworks.get(folder, {}).get("year", 0)  # Jahr übernehmen
            })
            # print (f"project.name: {folder}, project.preview: {preview}, project.files: {files}")
            # sort projects by year, newest first
        projects.sort(key=lambda p: p["year"], reverse=True)

    return render_template("index.html", projects=projects, artworks=artworks)
 
# Freeze the app, to deploy as static site
freezer = Freezer(app)
app.config['FREEZER_RELATIVE_URLS'] = True

if __name__ == "__main__":
#    app.run() #debug=True, port=5017)
    freezer.freeze()