import random
import datetime
from datetime import date
from flask import Flask, abort, render_template, redirect, url_for, flash, request, make_response
from flask_bootstrap import Bootstrap # Bootstrap5
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash
import smtplib
import os
import io
#from forms import CreatePostForm, RegisterForm, LoginForm, CommentForm, StocksForm, InteractiveMap

my_email = os.environ.get('MY_EMAIL')
my_email_pwd = os.environ.get('MY_EMAIL_PWD')


# APP ######################################
app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('APP_SECRET')
Bootstrap(app)
#Bootstrap5(app)

############################################
# Show Contact Site
@app.route("/contact", methods=["GET", "POST"])
def contact():
    if request.method == "POST":
        data = request.form
        send_email(data)
        return render_template("contact.html", msg_sent=True)
    return render_template("contact.html", msg_sent=False)

# mail senden
def send_email(data):
    name = data["name"]
    email = data["email"]
    phone = data["phone"]
    message = data["message"]

    email_content = f"Subject:New Message\n\nName: {name}\nEmail: {email}\nPhone: {phone}\nMessage:{message}"

    with smtplib.SMTP('smtp.gmail.com', 587) as connection:
        # tls to secure connection
        connection.starttls()
        connection.login(user=my_email, password=my_email_pwd)
        connection.sendmail(from_addr=my_email,
                            to_addrs=my_email,
                            msg=email_content.encode('utf-8'))


# Shows About Site #######################################
@app.route("/about")
def about():
    return render_template("about.html")

# Home #######################################
@app.route("/")
def index():
    art_path = os.path.join(app.static_folder, "assets", "img", "art")
    projects = []
    
    # Artwork Info
    artworks =  {
        "Strange Dogs": {
            "subtitle": "Acrylic on recycled Canvas, 95 x 135 cm",
            "year": 2020,
            "description": "The background shows a cross section of a tree and is the result of a photo processed with edge detection. If you look closely at the background, you can see an overpainted Udo Lindenberg."
        },
        "Falco": {
            "subtitle": "Acrylic on Canvas, 140 x 120 cm",
            "year": 2019,
            "description": "Falco's portrait was drawn by hand. The story behind it is the same as that of Marilyn. It was painted over 100 times until there was a certain resemblance to the original. This was too time-consuming for me, so I had to find a solution. That's how my vertical pen plotter project got started."
        },
        "Polygone 1": {
            "subtitle": "Acryl on Canvas, 100 x 120 cm",
            "year": 2020,
            "description": "The vertical plotter is made up of a Rasperry Pi running open-source software <a href='https://github.com/bertlr/vplotter'>(github)</a> that controls the movement of two stepper motors and a servo motor to draw polygons (generated by Python code) onto the canvas in two steps. As you can see, the first few attempts went beyond the image area and the drawing in the lower left corner did not start where it should have.",
        },
         "Girl with Headphones": {
            "subtitle": "Ink on paper, 60 x 84 cm",
            "year": 2024,
            "description": "I used AI to create the image template. For edge detection and style inspiration, I used DrawingBotV3 software. In the end, however, I only sketched the outlines with the vertical pen plotter because the full plot would have taken tens of hours. The rest I drew by hand.",
        },
        "Bird's Nest": {
            "subtitle": "Acrylic on Canvas, 160 x 120 cm",
            "year": 2023,
            "description": "AI is the dominant topic of our time, so I used AI to create some artwork. My workflow was simple: I analysed an AI-generated image using edge detection and converted the outlines of the pixel graphic into vectors. I then digitally retouched the image using a graphics tablet because the edge detection did not pick up all the relevant parts of the image as desired. Finally, I used a waterproof pen for the vplotter sketch and painted the image in acrylic.",
        },
        "Clint Stares at You": {
            "subtitle": "Acryl on Canvas, 100 x 120 cm",
            "year": 2020,
            "description": "The original process was to draw the portrait by hand on paper and then digitise it. I used Inkscape, an open-source vector graphics editor, to convert the pixel-based images into vectors so that I could scale them without losing quality. These vector paths can be converted to G-code, which is a programming language used to control automated machine tools like CNCs. G-code is the input format for the vertical plotter. The vertical plotter is made up of a Raspberry Pi, which is controlled by open-source software that you can find on GitHub. The Raspberry Pi reads the G-code and uses it to control the movement of two stepper motors and a servo motor, which draw the sketch on the canvas. The background was painted before I started. I used a waterproof pen for the Vplotter sketch and acrylic for the rest.",
        },
        "London DNA": {
            "subtitle": "Acrylic on recycled Ikea Canvas, 95 x 135 cm",
            "year": 2023,
            "description": "I used a recycled canvas (made of plastic) for this picture. This time I've documented the original picture and the individual processing steps. The DNA sketch is based on images taken with an electron microscope.",
        },
        "Bird's Nest Black Version": {
            "subtitle": "Ink / Watercolor on Paper, 60 x 84 cm",
            "year": 2024,
            "description": "3rd Version of Bird's Nest.",
        },
        "Bird's Nest Line Art": {
            "subtitle": "Ink on Paper, 51 x 72 cm",
            "year": 2024,
            "description": "The image template was basically the same as the Bird's Nest. This time I used DrawingBotV3, which turns images into stylised drawings and lets you export them as vector graphics. Just to note, I only plotted a small part of the result as the complete plotting would have taken over 30 hours, so I drew the rest by hand.",
        },
        "Polygone 2": {
            "subtitle": "Acryl on Canvas, 100 x 120 cm",
            "year": 2020,
            "description": "My second vertical pen plotter image. The polygons were automatically generated by a software and drawn onto the finished background in two steps. Obviously the white pen constantly loses colour intensity because it has a pump mechanism. Not recommended at all for a pen plotter, especially if you leave the room from time to time and let the plotter plot ...",
        },
        "Jellyfish": {
            "subtitle": "Ink on Paper, 59 x 84 cm",
            "year": 2021,
            "description": "Automatically generated line art plotted by a vertical pen plotter.",
        },
        "Just another Marilyn": {
            "subtitle": "Acrylic on Canvas, 100 x 140 cm",
            "year": 2019,
            "description": "The picture of Marilyn was painted in pre-vplotter times, so it took weeks to get it halfway right. Once it was on the wall, I found so many mistakes that it had to be reworked. This is a problem that many others may have experienced.",
        },
        "Flamingo Attack": {
            "subtitle": "Ink on Paper, 60 x 84 cm",
            "year": 2019,
            "description": "Hitchcock's The Birds 2: Revenge of the Flamingos.",
        },
        "Samurai Girl": {
            "subtitle": "Acryl on Canvas, 140 x 120 cm",
            "year": 2023,
            "description": "Hitchcock's The Birds 2: Revenge of the Flamingos.",
        },
        "Basset Hound": {
            "subtitle": "Acrylic on Canvas, 100 x 135 cm",
            "year": 2024,
            "description": "Impassivity in folds.",
        },
        "Three Apes": {
            "subtitle": "Ink on Paper, 60 x 84 cm",
            "year": 2024,
            "description": "Three apes waiting for the end of the world.",
        },
        "Vietnamese Dog": {
            "subtitle": "Chalk Paint/Watercolor/Wax Crayon on Recycled Canvas, 95 x 135 cm",
            "year": 2024,
            "description": "Nothing more to say.",
        },
        "Klimt":{
            "subtitle": "Chalk Paint/Watercolor/Acrylic/Wax Crayon on Recycled Canvas, 95 x 135 cm",
            "year": 2025,
            "description": "Nothing more to say.",
        }
    }


    for folder in sorted(os.listdir(art_path)):
        folder_path = os.path.join(art_path, folder)
        print(f"Checking folder: {folder_path}")
        if os.path.isdir(folder_path):
            files = sorted(os.listdir(folder_path))
            # print(f"Processing folder: {folder}")
            files = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.webp','.mp4', '.mov', '.webm'))]
            
            if files:
                preview = f'assets/img/art/{folder}/{files[0]}'  # first image as preview
                # print(f"Preview files: {preview}")
            else:
                continue

            projects.append({
                "name": folder,
                "preview": preview, # first image or video as preview
                "files": files,
            })
            # print (f"project.name: {folder}, project.preview: {preview}, project.files: {files}")

    return render_template("index.html", projects=projects, artworks=artworks)


if __name__ == "__main__":
    app.run( debug=True, port=5017)
