import random
import datetime
from datetime import date
from flask import Flask, abort, render_template, redirect, url_for, flash, request, make_response
from flask_bootstrap import Bootstrap # Bootstrap5
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash
import smtplib
import os
import io
#from forms import CreatePostForm, RegisterForm, LoginForm, CommentForm, StocksForm, InteractiveMap

my_email = os.environ.get('MY_EMAIL')
my_email_pwd = os.environ.get('MY_EMAIL_PWD')


# APP ######################################
app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('APP_SECRET')
Bootstrap(app)
#Bootstrap5(app)

############################################
# Show Contact Site
@app.route("/contact", methods=["GET", "POST"])
def contact():
    if request.method == "POST":
        data = request.form
        send_email(data)
        return render_template("contact.html", msg_sent=True)
    return render_template("contact.html", msg_sent=False)

# mail senden
def send_email(data):
    name = data["name"]
    email = data["email"]
    phone = data["phone"]
    message = data["message"]

    email_content = f"Subject:New Message\n\nName: {name}\nEmail: {email}\nPhone: {phone}\nMessage:{message}"

    with smtplib.SMTP('smtp.gmail.com', 587) as connection:
        # tls to secure connection
        connection.starttls()
        connection.login(user=my_email, password=my_email_pwd)
        connection.sendmail(from_addr=my_email,
                            to_addrs=my_email,
                            msg=email_content.encode('utf-8'))


# Shows About Site #######################################
@app.route("/about")
def about():
    return render_template("about.html")

# Home #######################################
@app.route("/")
def index():
    art_path = os.path.join(app.static_folder, "assets", "img", "art")
    projects = []
    
    # Artwork Info
    artworks =  {
        "Strange Dogs": {
            "subtitle": "Acrylic on recycled Canvas, 95 x 135 cm",
            "year": 2020,
            "description": "The background is a cross section of a tree, created using edge detection on a photo. If you look closely, you can see an overpainted Udo Lindenberg in the background."
        },
        "Falco": {
            "subtitle": "Acrylic on Canvas, 140 x 120 cm",
            "year": 2019,
            "description": "Falco's portrait was drawn by hand. The story behind it is similar to that of Marilyn's portrait. It was painted over one hundred times until it bore a certain resemblance to the original.<br>This process was too time-consuming, so I had to find a solution. That's how I started working on my vertical pen plotter project."
        },
        "Polygone 1": {
            "subtitle": "Acryl on Canvas, 100 x 120 cm",
            "year": 2020,
            "description": "This is my first image made with a vertical pen plotter.<br>The plotter uses a Raspberry Pi to run open-source software <a href='https://github.com/bertlr/vplotter'>(github)</a> that controls two stepper motors and a servo motor. These motors draw polygons (generated by Python code) onto the canvas in two steps.<br>As you can see in the picture, the first few attempts went beyond the image area, and the drawing in the lower left corner did not start where it should have. You might not have noticed this if I hadn't mentioned it.",
        },
         "Girl with Headphones": {
            "subtitle": "Ink on paper, 60 x 84 cm",
            "year": 2024,
            "description": "I used AI to create the image template. I used DrawingBotV3 software for edge detection and style inspiration.<br>Ultimately, however, I only sketched the outlines with the vertical pen plotter because completing the full plot would have taken tens of hours. I drew the rest by hand.",
        },
        "Bird's Nest": {
            "subtitle": "Acrylic on Canvas, 160 x 120 cm",
            "year": 2023,
            "description": "AI is the dominant topic of our time, so I used it to create some artwork. My workflow was simple. First, I analyzed an AI-generated image using edge detection to convert the outlines of the pixel graphic into vectors. Then, I digitally retouched the image with a graphics tablet because edge detection did not pick up all the desired parts of the image. Finally, I used a waterproof pen for the plotter sketch and painted the image with acrylics.",
        },
        "Clint Stares at You": {
            "subtitle": "Acryl on Canvas, 100 x 120 cm",
            "year": 2020,
            "description": "The portrait was drawn by hand on paper and then digitized. I used the open-source vector graphics editor Inkscape to convert the pixel-based images into vectors so that I could scale them without losing quality. These vector paths can be converted into G-code. G-code is a programming language used to control automated machine tools such as CNC machines. G-code is the input format for the vertical plotter.<br>This consists of a Raspberry Pi controlled by open-source software. The software is available on GitHub. The Raspberry Pi reads the G-code and uses it to control the movement of two stepper motors and a servo motor. These draw the sketch onto the canvas.<br>The background was painted before the plotter drew. I used a waterproof pen for the plotter sketch and acrylic paint for the rest.",
        },
        "London DNA": {
            "subtitle": "Acrylic on recycled Ikea Canvas, 95 x 135 cm",
            "year": 2023,
            "description": "For this picture, I used a recycled canvas made of plastic. This time, I documented both the original picture and the individual processing steps.<br>The DNA sketch is based on electron microscope images.",
        },
        "Bird's Nest Black Version": {
            "subtitle": "Ink / Watercolor on Paper, 60 x 84 cm",
            "year": 2024,
            "description": "3rd Version of Bird's Nest.",
        },
        "Bird's Nest Line Art": {
            "subtitle": "Ink on Paper, 51 x 72 cm",
            "year": 2024,
            "description": "The image template was essentially the same as the Bird's Nest.<br>This time, I used DrawingBotV3, which converts images into stylized drawings and allows you to export them as vector graphics. Note that I only plotted a small part of the result, as plotting the entire image would have taken over 30 hours. I drew the rest by hand.",
        },
        "Polygone 2": {
            "subtitle": "Acryl on Canvas, 100 x 120 cm",
            "year": 2020,
            "description": "This is my second vertical pen plotter image.<br>The polygons were generated automatically by software and drawn onto the finished background in two steps.<br>The white pen obviously loses color intensity because it has a pump mechanism. This is not at all recommended for a pen plotter, especially if you leave the room from time to time and let the plotter do its work.",
        },
        "Jellyfish": {
            "subtitle": "Ink on Paper, 59 x 84 cm",
            "year": 2021,
            "description": "Automatically generated line art plotted by a vertical pen plotter.",
        },
        "Just another Marilyn": {
            "subtitle": "Acrylic on Canvas, 100 x 140 cm",
            "year": 2019,
            "description": "The picture of Marilyn was painted before the times of the plotter, so it took weeks to get it halfway right. Once it was on the wall, I noticed so many errors that I had to rework it. Many others may have experienced this problem.",
        },
        "Flamingo Attack": {
            "subtitle": "Ink on Paper, 60 x 84 cm",
            "year": 2023,
            "description": "Hitchcock's The Birds 2: Revenge of the Flamingos.",
        },
        "Samurai Girl": {
            "subtitle": "Acryl on Canvas, 140 x 120 cm",
            "year": 2023,
            "description": "I used AI to create the image of the girl. I used DrawingBotV3 software for edge detection.<br>This time, I tried to create more depth by choosing a narrow street lined with houses as the perspective.",
        },
        "Basset Hound": {
            "subtitle": "Acrylic on Canvas, 100 x 135 cm",
            "year": 2024,
            "description": "Impassivity in folds.",
        },
        "Three Apes": {
            "subtitle": "Ink on Paper, 60 x 84 cm",
            "year": 2024,
            "description": "Three apes waiting for the end of the world.",
        },
        "Vietnamese Dog": {
            "subtitle": "Chalk Paint/Watercolor/Wax Crayon on Recycled Canvas, 95 x 135 cm",
            "year": 2024,
            "description": "Nothing more to say.",
        },
        "Bloch's Cousin":{
            "subtitle": "Mixed Media on Recycled Canvas, 100 x 140 cm",
            "year": 2025,
            "description": ".",
        }
    }


    for folder in sorted(os.listdir(art_path)):
        folder_path = os.path.join(art_path, folder)
        print(f"Checking folder: {folder_path}")
        if os.path.isdir(folder_path):
            files = sorted(os.listdir(folder_path))
            # print(f"Processing folder: {folder}")
            files = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.webp','.mp4', '.mov', '.webm'))]
            
            if files:
                preview = f'assets/img/art/{folder}/{files[0]}'  # first image as preview
                # print(f"Preview files: {preview}")
            else:
                continue

            projects.append({
                "name": folder,
                "preview": preview, # first image or video as preview
                "files": files,
                "year": artworks.get(folder, {}).get("year", 0)  # Jahr übernehmen
            })
            # print (f"project.name: {folder}, project.preview: {preview}, project.files: {files}")
            # sort projects by year, newest first
            projects.sort(key=lambda p: p["year"], reverse=True)

    return render_template("index.html", projects=projects, artworks=artworks)


if __name__ == "__main__":
    app.run( debug=True, port=5017)
